# Generated by Django 5.0.6 on 2024-07-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=20)),
                ('e', models.EmailField(max_length=254)),
                ('m', models.CharField(max_length=20)),
            ],
        ),
    ]
