# Generated by Django 5.0.6 on 2024-07-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rec_delete_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rec',
            old_name='messaage',
            new_name='message',
        ),
    ]
